### ISSUE TITLE
F# support difficulty?

### ISSUE THREAD

**Issue by nathanaeljones** [facebook/pfff#108]
I know that F# is a bit like OCaml, but I'm not an expert in either. Can anyone comment on the difficulty/scope of adding F# support?

**Comment by aryx** [comment]
If you want precise semantic information I recommend to look for special flags in the fsharp compiler that can generate metadata about the compiled files. That's what I currently do for Java (I analyze the bytecode .class files more than the .java), OCaml (I analyze more the .cmt files than the .ml), and also partially for C (I abuse the clang compiler to generate the full typed AST).

**Comment by aryx** [comment]
The alternative is to parse yourself F#, which can take a week, and then write a typechecker which can also take a week.

**Comment by nathanaeljones** [comment]
Thanks, very helpful!

**Comment by aryx** [comment]
for ocaml I use the -bin_annot flag. Maybe there is something similar for F#. There is good Visual studio support for F# so I guess they must have similar flags.

**Comment by phooji** [comment]
Closing because this looks like it's been addressed; please let me know if I'm missing something.
