### ISSUE TITLE
No tagged release in 7+ months and 0.28.1 cannot build hhvm 3.6 hacktools

### ISSUE THREAD

**Issue by mtorromeo** [facebook/pfff#112]
Please tag a stable release that is capable of compiling hhvm 3.6 hacktools.
I am maintaining the pfff and hhvm packages on Archlinux and this complicates things.

Thanks

**Comment by aryx** [comment]
can trunk compile those tools?
If yes I can just create a new tag release.

**Comment by mtorromeo** [comment]
Yes, I had to package a trunk version and everything worked fine.

**Comment by aryx** [comment]
here it is: https://github.com/facebook/pfff/releases/tag/v0.29

**Comment by mtorromeo** [comment]
Thanks a lot!

**Comment by aryx** [comment]
prego
