### ISSUE TITLE
make fails on mac OS X Yosemite

### ISSUE THREAD

**Issue by anthcp** [facebook/pfff#133]
ocamlc.opt -g -thread -dtypes -w +A-4-29-6-45-41-44-48 -warn-error +a  -bin-annot -absname   -I ../commons   -c figures.mli
ocamlc.opt -g -thread -dtypes -w +A-4-29-6-45-41-44-48 -warn-error +a  -bin-annot -absname   -I ../commons   -c figures.ml
ocamlc.opt -g -thread -dtypes -w +A-4-29-6-45-41-44-48 -warn-error +a  -bin-annot -absname   -I ../commons   -c simple_color.mli
ocamlc.opt -g -thread -dtypes -w +A-4-29-6-45-41-44-48 -warn-error +a  -bin-annot -absname   -I ../commons   -c simple_color.ml
File "/Users/anthcp/mycode/pfff/pfff/h_visualization/simple_color.ml", line 914, characters 3-5:
Error: Unbound value |>
make[2]: *** [simple_color.cmo] Error 2
make[1]: *** [rec] Error 1
make: *** [all] Error 2

**Comment by hhugo** [comment]
you need ocaml >= 4.01

**Comment by anthcp** [comment]
Thanks, just checked and I have "The OCaml toplevel, version 4.00.1"

**Comment by xennygrimmato** [comment]
make fails with OCaml 4.02.3 as well.
