### ISSUE TITLE
Issue compiling within Homebrew formula

### ISSUE THREAD

**Issue by molovo** [facebook/pfff#136]
I'm putting together a Homebrew formula to make this a bit easier to compile for everything. I'm having some issues with getting the binaries to compile within the Homebrew install environment. If anyone has any idea what's causing the issues I'd appreciate any input. I've raised an [issue](https://github.com/Homebrew/homebrew/issues/46061) against the Homebrew repository containing the details.

**Comment by aryx** [comment]
It's the MAKEFLAGS=-j8 used by default in your environment.
Can you use make -j1 as a short-term fix?

**Comment by molovo** [comment]
That's fixed it. Cheers @aryx
