### ISSUE TITLE
[spatch] Meta variables reformatted during patching

### ISSUE THREAD

**Issue by aik099** [facebook/pfff#140]
Patch code:

```
-X = $this->Application->recallObject(Y1, Y2, Y3);
+X =& $this->Application->recallObject(Y1, Y2, Y3);
```

Code that is patched:

```
<?php

$var = $this->Application->recallObject('test', null, array('key' => true));
```

After fixing the `array('key' => true)` becomes `array('key'=>true)` (spaces before and after `=>` are removed). I think this is incorrect to reformat code, that shouldn't be fixed as part of the patching.

**Comment by aryx** [comment]
Yes, this issue is mentioned on the wiki:
https://github.com/facebook/pfff/wiki/Spatch#spacing-issues

You can avoid the issue by rewriting the patch as
X 
-  =
+ =&
  $this->Application->recallObject(Y1, Y2, Y3);

**Comment by aik099** [comment]
@aryx , can you please use fenced code blocks, because GitHub has formatted your suggestion as Markdown and I get what was changed.

Also I'm not sure, but using `(...)` doesn't work and error is displayed. Because of that I hard to create 2 patches: one for mandatory arguments and one for mandatory + optional arguments.

**Comment by aik099** [comment]
I've tried rewriting patch like so:

```
-X = $this->Application->recallObject(Y1, Y2, Y3)
+X =&
 $this->Application->recallObject(Y1, Y2, Y3)
```

but I'm getting an error:

```
Fatal error: exception Failure("could not parse: X = $this->Application->recallObject(Y1, Y2, Y3)\n\n$this->Application->recallObject(Y1, Y2, Y3)\n")
```

**Comment by aik099** [comment]
The following patch:

```
-X
+X =&
 $this->Application->recallObject(Y1, Y2, Y3)
```

gives this error:

```
Fatal error: exception Failure("could not parse: X\n\n $this->Application->recallObject(Y1, Y2, Y3)\n")
```

**Comment by aryx** [comment]
`
  X
- =
+ =& 
  $this->Application->recallObject(Y1, Y2, Y3);
`

**Comment by aik099** [comment]
Thanks, that worked perfectly.

I'm not sure why, but following was also done (spaces after comma in `list(...)` construct):
```
list(
-				$product_id, $backorder, $qty, $price, , , , $order_item_id, $options_salt, $item_data, $cost
+				$product_id, $backorder, $qty, $price,,,, $order_item_id, $options_salt, $item_data, $cost
 				) = $operation_row;
```
