### ISSUE TITLE
Trying to build on macOS 10.12

### ISSUE THREAD

**Issue by smithrb** [facebook/pfff#145]
Receiving the following during make:

File "/Users/razbear/Documents/dev/pfff/lang_nw/parsing/lexer_nw.mll", line 140, characters 15-21:
Warning 52: the argument of this constructor should not be matched against a
constant pattern; the actual value of the argument could change
in the future.

Any ideas?

**Comment by aryx** [comment]
It's a new warning of a recent version of ocaml probably.
It just points out bad practice. You can replace Failure("hd") by Failure(_)
and the warning should disappear.

**Comment by smithrb** [comment]
Thanks - that fixed it.  Also had _ascii appends to string conversions...

Clean build finally, looking for examples now.

Thanks!
