### ISSUE TITLE
OSX Yosemite 10.10.5 + make error

### ISSUE THREAD

**Issue by henryli** [facebook/pfff#146]
ocamlmklib -oc camlzip zlibstubs.o \
            -L/usr/local/lib -lz
ocamlc -g -c zlib.mli
ocamlc -g -c zlib.ml
File "zlib.ml", line 49, characters 14-27:
Warning 3: deprecated: String.create
Use Bytes.create instead.
File "zlib.ml", line 50, characters 15-28:
Warning 3: deprecated: String.create
Use Bytes.create instead.
File "zlib.ml", line 72, characters 15-28:
Warning 3: deprecated: String.create
Use Bytes.create instead.
File "zlib.ml", line 91, characters 14-27:
Warning 3: deprecated: String.create
Use Bytes.create instead.
File "zlib.ml", line 92, characters 15-28:
Warning 3: deprecated: String.create
Use Bytes.create instead.
ocamlc -g -c zip.mli
ocamlc -g -c zip.ml
File "zip.ml", line 31, characters 10-23:
Warning 3: deprecated: String.create
Use Bytes.create instead.
File "zip.ml", line 76, characters 10-15:
Error: Multiple definition of the extension constructor name Error.
       Names must be unique in a given structure or signature.
make[2]: *** [zip.cmo] Error 2
make[1]: *** [rec] Error 1
make: *** [all] Error 2

**Comment by xennygrimmato** [comment]
Same error on Mac OS X 10.11.3.

**Comment by aryx** [comment]
I removed the duplicate exception.

**Comment by xennygrimmato** [comment]
Got the following error after this fix. Is there a difference between Errors and Fatal warnings?
```
Error: Some fatal warnings were triggered (2 occurrences)
make[2]: *** [php_vs_php.cmo] Error 2
make[1]: *** [rec] Error 1
make: *** [all] Error 2
```

**Comment by henryli** [comment]
same here:
ocamlc.opt -g -thread -dtypes -w +A-4-29-6-45-32 -warn-error +a -bin-annot -absname   -I ../../commons -I ../../commons/ocollection -I ../../commons/ocamlextra -I ../../h_program-lang -I ../../h_version-control -I ../../globals -I ../../external/ -I ../../matcher -I ../parsing   -c php_vs_php.ml
File "/Users/henry.li/softwares/facebook/pfff/lang_php/matcher/php_vs_php.ml", line 290, characters 17-33:
Warning 3: deprecated: String.lowercase
Use String.lowercase_ascii instead.
File "/Users/henry.li/softwares/facebook/pfff/lang_php/matcher/php_vs_php.ml", line 290, characters 38-54:
Warning 3: deprecated: String.lowercase
Use String.lowercase_ascii instead.
File "/Users/henry.li/softwares/facebook/pfff/lang_php/matcher/php_vs_php.ml", line 1:
Error: Some fatal warnings were triggered (2 occurrences)
make[2]: *** [php_vs_php.cmo] Error 2
make[1]: *** [rec] Error 1
make: *** [all] Error 2

**Comment by aryx** [comment]
I fixed it I think.
