### ISSUE TITLE
How command pfff output store in a file?

### ISSUE THREAD

**Issue by wikinee** [facebook/pfff#155]
I use pfff to analize project, like

./pfff -parse_cpp ~/MY_PROJECT_PATH/PROJECT_NAME

the output scroll the terminal, and How can I store it in a file

**Comment by aryx** [comment]
By using redirection?

./pfff -parse_cpp /path > output_file.

Maybe -parse_cpp use stderr to communicate parse error, so you want then to redirect stderr with

./pfff -parse_cpp /path 2> output_file
(it depends on which shell you use)

**Comment by wikinee** [comment]
@aryx THX, It's real use stderr!
