### ISSUE TITLE
wrong parsing of short form of ternary if with no spaces $rows?:false;

### ISSUE THREAD

**Issue by Techmind** [facebook/pfff#56]
echo '<?php $x = $rows?:false;' > test.php
sgrep -e 'reset(X->Y(...));' test.php
warning: parsing problem in /home/ibogunov/test.php

echo '<?php $x = $rows ? : false;' > test.php
sgrep -e 'reset(X->Y(...));' test.php

**Comment by phooji** [comment]
Closing since the discussion has moved to the pull request.
