### ISSUE TITLE
scheck needs graph file

### ISSUE THREAD

**Issue by dericofilho** [facebook/pfff#98]
Before it was possible to run scheck without graph file. Is there a command switch to re-enable this old behavior?

**Comment by pirminis** [comment]
+1

**Comment by richardkmiller** [comment]
+1

**Comment by designercat** [comment]
+1

**Comment by jbenoit2011** [comment]
+1 Any updates?

**Comment by cdaguerre** [comment]
@dericofilho May we ask why you closed this?

**Comment by dericofilho** [comment]
@cdaguerre I am not using pfff anymore

**Comment by cdaguerre** [comment]
Neither am I, specifically because of this. However other people still have the issue...

**Comment by jbenoit2011** [comment]
Actually yes.

*Julien BENOIT*
*PHP & JS developer @GuestToGuest <https://twitter.com/GuestToGuest>*
Paris, FR.
blog.julienbenoit.net
  <http://fr.linkedin.com/in/jbenoit2011>
<http://www.viadeo.com/profile/0021vk9j4z60jp63/>
<https://github.com/jbenoit2011>

2015-06-12 12:34 GMT+02:00 Christian Daguerre <notifications@github.com>:

**Comment by istana** [comment]
for those who searched for the answer - I posted it also here https://github.com/facebook/pfff/issues/151

> I was just able to run it. You need to build graph data first. For some reason scheck requires working directory to be the source code of the target. This should work:

```
mkdir ~/pfff_output
cd ~/phpsource
~/pfff/codegraph -lang php -derived_data -o ~/pfff_output/ -build ~/phpsource
~/pfff/scheck -lang php -with_graph_code ~/pfff_output/graph_code.marshall ~/phpsource
```
